### ISSUE TITLE
Complete samples

### ISSUE THREAD

**Issue by itsmostafa75** [ByteMysticRogue/sing-box-templates#2]
تشکر از وقتی که گذاتشین
امکان داره به این ریپوزتوری، پروتکل‌های زیر رو هم اضافه‌ کنید تا کاملترین در سطح وب بشه؟
با تشکر
Hysteria 1
Hysteria 2
Wireguard
Shadowsocks
Vless tls tcp
Vless tls grpc
Vless tls ws
Vless tls http upgrade

**Comment by ByteMysticRogue** [comment]
> تشکر از وقتی که گذاتشین امکان داره به این ریپوزتوری، پروتکل‌های زیر رو هم اضافه‌ کنید تا کاملترین در سطح وب بشه؟ با تشکر Hysteria 1 Hysteria 2 Wireguard Shadowsocks Vless tls tcp Vless tls grpc Vless tls ws Vless tls http upgrade

سلام، در آینده تکمیل میشه.
